### PR TITLE
Исправления

### PR DESCRIPTION
**Pull request by serejkaaa512**
Переделал кривые фразы, ошибки, форматирование.

---

This change is [Reviewable](https://reviewable.io/reviews/rurust/tlborm/4)

### CODE REVIEW

**Comment by mkpankov** [comment]
Reviewed 1 of 30 files at r1.
Review status: 1 of 30 files reviewed at latest revision, 5 unresolved discussions.

---

_[text/aeg-ook.md, line 43 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEZyzC99zOtBBRqf4OV:-KEZyzC99zOtBBRqf4OW:786536135) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L43)):_
Давай поставим ссылку на русскую википедию?

---

_[text/aeg-ook.md, line 50 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEZzzUS0hJjx-3mLzE0:-KEZzzUS0hJjx-3mLzE1:183232953) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L50)):_
Это не поля. Предлагаю "объявления".

---

_[text/aeg-ook.md, line 141 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_8NOH6BpapvtUG5Ka:-KE_8NOH6BpapvtUG5Kb:-1422131140) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L141)):_
Предлагаю "так, как описано в разделе ..."

---

_[text/aeg-ook.md, line 248 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_8v5ere_i9uQvHwpo:-KE_8v5ere_i9uQvHwpp:-729561197) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L248)):_
Кириллические ссылки не работают, нужна латиница. Здесь и далее

---

_[text/aeg-ook.md, line 440 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_9QYpkpnm0S5Fc6tL:-KE_9QYpkpnm0S5Fc6tM:231310921) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L440)):_
было правильно

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by serejkaaa512** [comment]
Review status: 0 of 30 files reviewed at latest revision, 5 unresolved discussions.

---

_[text/aeg-ook.md, line 43 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEZyzC99zOtBBRqf4OV:-KE_fLNfNd5hKyPpno4Q:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L43)):_
Done.

---

_[text/aeg-ook.md, line 50 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEZzzUS0hJjx-3mLzE0:-KE_fMCIOciKrwoU6RqZ:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L50)):_
Done.

---

_[text/aeg-ook.md, line 141 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_8NOH6BpapvtUG5Ka:-KE_fNvCmomrIgw5dAPI:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L141)):_
Done.

---

_[text/aeg-ook.md, line 248 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_8v5ere_i9uQvHwpo:-KE_fP-XNO-nnlxuAP3q:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L248)):_
Done.

---

_[text/aeg-ook.md, line 440 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_9QYpkpnm0S5Fc6tL:-KE_fPrd4QMDoXPEd2k9:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L440)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by mkpankov** [comment]
Reviewed 2 of 30 files at r1, 1 of 1 files at r2.
Review status: 3 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

_[text/aeg-ook.md, line 440 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_9QYpkpnm0S5Fc6tL:-KEc27X_f2hn4r-j7n47:-311118334) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L440)):_
Не об этом комментарий. "В дополнение" - правильно.

---

_[text/blk-ast-coercion.md, line 1 [r2]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEc43TBQ5c7KfltD543:-KEc43TBQ5c7KfltD544:-1619967074) ([raw file](https://github.com/rurust/tlborm/blob/2ea27ff44405492f969ba2c50c9b8eeff2f1c212/text/blk-ast-coercion.md#L1)):_
Что приводится к AST?

По-моему речь всё же о преобразованиях синтаксического дерева - "Преобразования AST"

Здесь и далее

---

_[text/blk-ast-coercion.md, line 33 [r2]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEc3y5K9gCbUstLYL00:-KEc3y5LFlLECY8hoCm6:-200247577) ([raw file](https://github.com/rurust/tlborm/blob/2ea27ff44405492f969ba2c50c9b8eeff2f1c212/text/blk-ast-coercion.md#L33)):_
Ссылки должны быть на английском. Проверь весь PR пожалуйста

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by serejkaaa512** [comment]
Review status: 1 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

_[text/aeg-ook.md, line 440 [r1]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KE_9QYpkpnm0S5Fc6tL:-KEe223zuKCFFkOWpA0Q:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/f9e71685a4f6809632143a821206d9db78939b70/text/aeg-ook.md#L440)):_
Done.

---

_[text/blk-ast-coercion.md, line 1 [r2]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEc43TBQ5c7KfltD543:-KEe26AtbnqRZob_Gszv:-882022024) ([raw file](https://github.com/rurust/tlborm/blob/2ea27ff44405492f969ba2c50c9b8eeff2f1c212/text/blk-ast-coercion.md#L1)):_
Приводится метапеременная к особому виду AST - выражению, элементу, паттерну, утверждению. То есть это особый вид приведение типа на входе. Слово "преобразования" мне кажется не совсем отображает смысл этого.

---

_[text/blk-ast-coercion.md, line 33 [r2]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEc3y5K9gCbUstLYL00:-KEe2y1efoNByxiHrFst:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/2ea27ff44405492f969ba2c50c9b8eeff2f1c212/text/blk-ast-coercion.md#L33)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by mkpankov** [comment]
Reviewed 1 of 30 files at r1, 2 of 10 files at r3.
Review status: 4 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

_[text/blk-ast-coercion.md, line 1 [r2]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEc43TBQ5c7KfltD543:-KEe8l-V6cWysLEwpiIt:-15037193) ([raw file](https://github.com/rurust/tlborm/blob/2ea27ff44405492f969ba2c50c9b8eeff2f1c212/text/blk-ast-coercion.md#L1)):_
Понял, согласен

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by mkpankov** [comment]
Reviewed 2 of 30 files at r1, 1 of 10 files at r3.
Review status: 7 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

_[text/blk-enum-parsing.md, line 80 [r3]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEfsuxIGPNPDVYo-0-Z:-KEfsuxJHgHJ9MJBffm-:-1007818050) ([raw file](https://github.com/rurust/tlborm/blob/bcb850e8f040143ba56bbb658c385025b012890b/text/blk-enum-parsing.md#L80)):_
Длина строки

---

_[text/mbe-macro-rules.md, line 31 [r3]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEftwHa2HqttcjByaUf:-KEftwHa2HqttcjByaUg:-695765636) ([raw file](https://github.com/rurust/tlborm/blob/bcb850e8f040143ba56bbb658c385025b012890b/text/mbe-macro-rules.md#L31)):_
По крайней мере, ничего не появляется в AST; ...

---

_[text/mbe-macro-rules.md, line 87 [r3]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEfuOXsVNa422m1XdKG:-KEfuOXtDtwbPBCdTCQL:-776406072) ([raw file](https://github.com/rurust/tlborm/blob/bcb850e8f040143ba56bbb658c385025b012890b/text/mbe-macro-rules.md#L87)):_
запятая не нужна

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by serejkaaa512** [comment]
Review status: 7 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

_[text/blk-ast-coercion.md, line 1 [r2]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEc43TBQ5c7KfltD543:-KEg45O3LXWQwYMxUHRt:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/2ea27ff44405492f969ba2c50c9b8eeff2f1c212/text/blk-ast-coercion.md#L1)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by serejkaaa512** [comment]
Review status: 5 of 30 files reviewed at latest revision, 3 unresolved discussions.

---

_[text/blk-enum-parsing.md, line 80 [r3]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEfsuxIGPNPDVYo-0-Z:-KEjLaPJyyzY3fY7JNmU:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/bcb850e8f040143ba56bbb658c385025b012890b/text/blk-enum-parsing.md#L80)):_
Done.

---

_[text/mbe-macro-rules.md, line 31 [r3]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEftwHa2HqttcjByaUf:-KEjLc6WEjFBxKrY4V6-:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/bcb850e8f040143ba56bbb658c385025b012890b/text/mbe-macro-rules.md#L31)):_
Done.

---

_[text/mbe-macro-rules.md, line 87 [r3]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEfuOXsVNa422m1XdKG:-KEjLe5eq8ASdK4YpeRj:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/bcb850e8f040143ba56bbb658c385025b012890b/text/mbe-macro-rules.md#L87)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by mkpankov** [comment]
Reviewed 4 of 30 files at r1, 2 of 2 files at r4.
Review status: 11 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

_[text/mbe-min-captures-and-expansion-redux.md, line 42 [r4]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEmMIm6sO9qkC-bYaDr:-KEmMIm6sO9qkC-bYaDs:139490691) ([raw file](https://github.com/rurust/tlborm/blob/476d29cfdd2d66d49212b7a4b75fb482c323ebc1/text/mbe-min-captures-and-expansion-redux.md#L42)):_
В дополнение

---

_[text/mbe-min-import-export.md, line 32 [r4]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEmNQgb3jSW20UWOAjF:-KEmNQgb3jSW20UWOAjG:1107550126) ([raw file](https://github.com/rurust/tlborm/blob/476d29cfdd2d66d49212b7a4b75fb482c323ebc1/text/mbe-min-import-export.md#L32)):_
Более точно так: 

X! и Y! не определены здесь, но всё равно экспортируются, несмотря на то, что `mod macros` является приватным.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by serejkaaa512** [comment]
Review status: 9 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

_[text/mbe-min-captures-and-expansion-redux.md, line 42 [r4]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEmMIm6sO9qkC-bYaDr:-KEoGXuWS0F5U4TrOeEu:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/476d29cfdd2d66d49212b7a4b75fb482c323ebc1/text/mbe-min-captures-and-expansion-redux.md#L42)):_
Done.

---

_[text/mbe-min-import-export.md, line 32 [r4]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEmNQgb3jSW20UWOAjF:-KEoGZsF8fn3adBeT0zv:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/476d29cfdd2d66d49212b7a4b75fb482c323ebc1/text/mbe-min-import-export.md#L32)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by mkpankov** [comment]
Вуху!

---

Reviewed 12 of 30 files at r1, 7 of 10 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

_[text/mbe-min-README.md, line 4 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEvBE7px_2hHXwvCPeo:-KEvBE7px_2hHXwvCPep:2116353130) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-min-README.md#L4)):_
проблем в ней 

(системе макросов)

---

_[text/mbe-README.md, line 9 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwsl09pFtkHJuG9nCU:-KEwsl09pFtkHJuG9nCV:-1007818050) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-README.md#L9)):_
Длина строки

---

_[text/mbe-syn-macros-in-the-ast.md, line 30 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwtMZh60QcMqTxX4vp:-KEwtMZh60QcMqTxX4vq:977149952) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-syn-macros-in-the-ast.md#L30)):_
третьей

---

_[text/mbe-syn-macros-in-the-ast.md, line 68 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwtSoGFLGO8wwWCLQS:-KEwtSoGFLGO8wwWCLQT:-1861885069) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-syn-macros-in-the-ast.md#L68)):_
как будто (без дефиса)

---

_[text/mbe-syn-source-analysis.md, line 34 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwtxcAkgygSYloo2EE:-KEwtxcB57IphsrvHYCo:1462915854) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-syn-source-analysis.md#L34)):_
"эффективно" - "на самом деле"

---

_[text/pat-callbacks.md, line 29 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwuS_7wrHQ1ye_9NSH:-KEwuS_7wrHQ1ye_9NSI:-1459667849) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-callbacks.md#L29)):_
Но макросы не разбиваются на модули.

Я думаю стоит оставить это предложение как было.

---

_[text/pat-incremental-tt-munchers.md, line 35 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwupjJOFi3Q8094lpc:-KEwupjJOFi3Q8094lpd:-2025064226) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-incremental-tt-munchers.md#L35)):_
Здесь "паттерн" - это "шаблон программирования", но точно не "образец".

---

_[text/pat-provisional.md, line 105 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwvZgariILUVnjyJNm:-KEwvZgb_FpQlyhdi2rO:-1690474395) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-provisional.md#L105)):_
правила

---

_[text/pat-tt-bundling.md, line 50 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwvsNXcYBknWxt69hz:-KEwvsNXcYBknWxt69i-:1526443744) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-tt-bundling.md#L50)):_
понадобиться

---

_[text/pat-visibility.md, line 6 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEww-SYsiDYgypApA1A:-KEww-SYsiDYgypApA1B:-1600246244) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-visibility.md#L6)):_
совпадений

---

_[text/pim-README.md, line 13 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwwAsDeYeh_GOpGOit:-KEwwAsDeYeh_GOpGOiu:1180237347) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pim-README.md#L13)):_
Было лучше. Теперь непонятно, что за "маленький контекст". Как будто это понятие, описываемое дальше в книге.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4#-:-KEwwq-vk7GdQVNiIumt:430533965)_

**Comment by serejkaaa512** [comment]
ОуйЕЕ! Килл олл зе вайт мен!!

---

Review status: 20 of 30 files reviewed at latest revision, 11 unresolved discussions.

---

_[text/mbe-min-README.md, line 4 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEvBE7px_2hHXwvCPeo:-KF2iRz9ZMNcuXvTYtHZ:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-min-README.md#L4)):_
Done.

---

_[text/mbe-README.md, line 9 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwsl09pFtkHJuG9nCU:-KF2iTFGptRr559NbLwV:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-README.md#L9)):_
Done.

---

_[text/mbe-syn-macros-in-the-ast.md, line 30 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwtMZh60QcMqTxX4vp:-KF2iVQs-Fj3huTQDt36:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-syn-macros-in-the-ast.md#L30)):_
Done.

---

_[text/mbe-syn-macros-in-the-ast.md, line 68 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwtSoGFLGO8wwWCLQS:-KF2iVp_U8lId2vuVjO6:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-syn-macros-in-the-ast.md#L68)):_
Done.

---

_[text/mbe-syn-source-analysis.md, line 34 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwtxcAkgygSYloo2EE:-KF2iY4UmbttrnA4rmSu:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/mbe-syn-source-analysis.md#L34)):_
Done.

---

_[text/pat-callbacks.md, line 29 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwuS_7wrHQ1ye_9NSH:-KF2iqDXzxPgzVBApJqy:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-callbacks.md#L29)):_
Done.

---

_[text/pat-incremental-tt-munchers.md, line 35 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwupjJOFi3Q8094lpc:-KF2ic2ps9XiXUXwwG2r:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-incremental-tt-munchers.md#L35)):_
Done.

---

_[text/pat-provisional.md, line 105 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwvZgariILUVnjyJNm:-KF2ictWxIFtv7MiV3NG:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-provisional.md#L105)):_
Done.

---

_[text/pat-tt-bundling.md, line 50 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwvsNXcYBknWxt69hz:-KF2iedNxbAsORL4K58A:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-tt-bundling.md#L50)):_
Done.

---

_[text/pat-visibility.md, line 6 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEww-SYsiDYgypApA1A:-KF2ig1Xw4gG5Dl8en5Q:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-visibility.md#L6)):_
Done.

---

_[text/pim-README.md, line 13 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwwAsDeYeh_GOpGOit:-KF2ijLJZZ7kGBBuiaMZ:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pim-README.md#L13)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4#-:-KF2isBkIj5SIiZ3I9qk:429082551)_

**Comment by mkpankov** [comment]
Reviewed 10 of 10 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[text/pat-callbacks.md, line 29 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwuS_7wrHQ1ye_9NSH:-KF2w3kKw4QqCclaSVAN:-343615754) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-callbacks.md#L29)):_
Серёжа, я имел ввиду, что мне не понятен новый вариант предложения. Я возразил - "но макросы не разбиваются на модули" :)

Предлагаю вернуть вариант до всех правок.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by serejkaaa512** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[text/pat-callbacks.md, line 29 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwuS_7wrHQ1ye_9NSH:-KF3k5s8efxy0yjM5Jwa:30485676) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-callbacks.md#L29)):_
Так именно смысл этого предложения и в этом - макросы не поддерживают разбиение на модули ;)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by mkpankov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[text/pat-callbacks.md, line 29 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwuS_7wrHQ1ye_9NSH:-KF3m9TMlNBhdTHalbwg:1101817445) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-callbacks.md#L29)):_
Оригинал говорит не об этом. "This can make modularising macros very difficult." - буквально переводится так, как изначально было написано - "Это могло бы сделать модуляризацию макросов очень сложной."

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by serejkaaa512** [comment]
Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

_[text/pat-callbacks.md, line 29 [r5]](https://reviewable.io:443/reviews/rurust/tlborm/4#-KEwuS_7wrHQ1ye_9NSH:-KF3rqvJ0xBKgBbpWY3u:-499146009) ([raw file](https://github.com/rurust/tlborm/blob/721cb49f7f0a6cce5a0aedad116a06ccf96e7fe4/text/pat-callbacks.md#L29)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Comment by mkpankov** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/rurust/tlborm/4)_

**Pull request merged**
